In [ ]:
%pip install autoviz

In [ ]:
py -3.14 -m pip install autoviz

SyntaxError: invalid syntax (384365232.py, line 1)

In [ ]:
import seaborn as sns
import pandas as pd
df=sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
df.to_csv('tips.csv')

In [ ]:
from autoviz.AutoViz_Class import AutoViz_Class

In [ ]:
!pip install sweetviz

In [2]:
import seaborn as sn
df = sn.load_dataset("titanic")

In [3]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [6]:
import sweetviz as sv
my_report = sv.analyze(df)
my_report.show_html

                                             |          | [  0%]   00:00 -> (? left)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')